
export const pokimonContants = {
    POKIMON_LIST_LOADING: "POKIMON_LIST_LOADING",
    POKIMON_LIST_SUCCESS:"POKIMON_LIST_SUCCESS",
    POKIMON_LIST_FAIL: "POKIMON_LIST_FAIL",
    POKEMON_BLOG_DETAIL_LOADING: "POKEMON_BLOG_DETAIL_LOADING",
    POKEMON_BLOG_DETAIL_SUCCSESS: "POKEMON_BLOG_DETAIL_SUCCSESS",
    POKEMON_BLOG_DETAIL_FAIL: "POKEMON_BLOG_DETAIL_FAIL",
    POKEMON_SEARCH_RESULT_LOADING:"POKEMON_SEARCH_RESULT_LOADING",
    POKEMON_SEARCH_RESULT_SUCCESS:"POKEMON_SEARCH_RESULT_SUCCESS",
    POKEMON_SEARCH__RESULT_FAIL: "POKEMON_SEARCH__RESULT_FAIL",
    CLEAR_SEARCH_RESULT:"CLEAR_SEARCH_RESULT"
    
}